name: DevSecOps CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Python + cache pip
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      # 3) Dépendances + outils sécu
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety

      # 4) SAST (Bandit)
      - name: Run Bandit (SAST)
        run: |
          bandit -r . -q -x .venv,.git

      # 5) SCA (Safety)
      - name: Run Safety (SCA)
        run: |
          safety check -r requirements.txt --full-report

      # 6) Container Security (Trivy)
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0
        with:
          image-ref: 'docker.io/library/python:3.11-slim'
          format: 'table'
          exit-code: '1'            # échoue si vulnérabilités
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' # seuil conseillé

      # 7) IaC Security (Checkov)
      - name: Scan Terraform with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform
          framework: terraform
          quiet: true
          soft_fail: false          # échoue si findings
