name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      # --- 1. Checkout du repo ---
      - name: Checkout code
        uses: actions/checkout@v3

      # --- 2. Setup Python ---
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # --- 3. Installation des dépendances ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- 4. SAST (Static Application Security Testing) ---
      - name: Run Bandit (SAST)
        run: |
          pip install bandit
          bandit -r app.py

      # --- 5. SCA (Software Composition Analysis) ---
      - name: Run Safety (SCA)
        run: |
          pip install safety
          safety check --full-report

      # --- 6. Container Security (Trivy) ---
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/library/python:3.11-slim'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      # --- 7. IaC Security (Terraform files with Checkov) ---
      - name: Scan Terraform with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          quiet: true
