name: DevSecOps CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      # --- 1. Checkout du repo ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- 2. Setup Python ---
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            .github/workflows/requirements.txt

      # --- 3. Installation des dépendances ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
          # Outils sécurité utilisés plus bas
          pip install bandit safety

      # --- 4. SAST (Static Application Security Testing) ---
      - name: Run Bandit (SAST)
        run: |
          # Analyse récursive du dossier workflows (où est ton app.py)
          bandit -r .github/workflows -q -x .venv

      # --- 5. SCA (Software Composition Analysis) ---
      - name: Run Safety (SCA)
        run: |
          safety check -r .github/workflows/requirements.txt --full-report

      # --- 6. Container Security (Trivy) ---
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0
        with:
          image-ref: 'docker.io/library/python:3.11-slim'
          format: 'table'
          exit-code: '1'            # échoue le job si vulnérabilités (ajuste si besoin)
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' # seuil conseillé

      # --- 7. IaC Security (Terraform files with Checkov) ---
      - name: Scan Terraform with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .github/workflows/terraform
          quiet: true
          framework: terraform
          soft_fail: false          # échoue le job si findings (met à true si tu veux tolérer)
