# Utilise une image Python légère
FROM python:3.11-slim

# Définit le dossier de travail
WORKDIR /app

# Copie les fichiers
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# Expose le port Flask
EXPOSE 5000

# Commande de lancement
CMD ["python", "app.py"]
